from django.urls import path

from . import views
app_name="myapp"
urlpatterns = [
    path('', views.loginn),
    path('adm_add_batch/', views.adm_add_batch),
    path('adm_add_class/', views.adm_add_class),
    path('adm_home/', views.adm_home),
    path('adm_add_fee_structure/', views.adm_add_fee_structure),
    path('adm_add_monthly_fee/', views.adm_add_monthly_fee),
    path('adm_add_monthly_fees/', views.adm_add_monthly_fees),
    path('adm_add_tutors_attendence/',views.adm_add_tutors_attendence),
    path('adm_add_student/', views.adm_add_student),
    path('adm_add_subject/', views.adm_add_subject),
    path('adm_add_timetable/', views.adm_add_timetable),
    path('adm_add_tutor/', views.adm_add_tutor),
    path('adm_add_tutors_subject/', views.adm_add_tutors_subject,name="adm_add_tutors_subject"),
    path('adm_add_tutors_subject_post/',views.adm_add_tutors_subject_post),
    path('adm_add_tutors_salary/', views.adm_add_tutors_salary),
    path('adm_add_vacancy/', views.adm_add_vacancy),
    path('adm_due_report/', views.adm_due_report),
    path('adm_give_reply/', views.adm_give_reply),
    path('adm_update_batch/<str:pk>', views.adm_update_batch),
    path('adm_update_class/<str:pk>', views.adm_update_class),
    path('adm_update_fee_structure/<str:pk>', views.adm_update_fee_structure),
    path('adm_update_fee_structure_post/', views.adm_update_fee_structure_post),
    path('adm_update_student/', views.adm_update_student),
    path('adm_update_tutors_attendence/<str:pk>', views.adm_update_tutors_attendence),
    path('adm_update_tutors_attendence_post/', views.adm_update_tutors_attendence_post),

    path('adm_update_subject/<str:pk>', views.adm_update_subject),
    path('adm_update_subject_post/', views.adm_update_subject_post),
    path('adm_update_timetable/', views.adm_update_timetable),
    path('adm_update_tutor/<str:pk>', views.adm_update_tutor),
    path('adm_update_tutors_subject/', views.adm_update_tutors_subject),
    path('adm_update_vacancy/<str:pk>', views.adm_update_vacancy),
    path('adm_update_vacancy_post/', views.adm_update_vacancy_post),
    path('adm_view_attendence_of_tutors/', views.adm_view_attendence_of_tutors),
    path('adm_view_attendence_of_tutors_del/<str:pk>', views.adm_view_attendence_of_tutors_del),
    path('adm_view_batch/', views.adm_view_batch),
    path('adm_view_batch_del/<str:pk>',views.adm_view_batch_del),
    path('adm_view_class/', views.adm_view_class),
    path('adm_view_class_del/<str:pk>',views.adm_view_class_del),
    path('adm_view_complaint/', views.adm_view_complaint),
    path('adm_view_fee_structure/', views.adm_view_fee_structure),
    path('adm_view_fee_structure_del/<str:pk>', views.adm_view_fee_structure_del),
    path('adm_view_feedback/', views.adm_view_feedback),
    path('adm_view_leave_request/', views.adm_view_leave_request),
    path('adm_view_monthly_fee_reports/', views.adm_view_monthly_fee_reports),
    path('adm_view_monthly_salary_reports/', views.adm_view_monthly_salary_reports),
    path('adm_view_student/', views.adm_view_student),
    path('adm_view_subject/', views.adm_view_subject),
    path('adm_view_subject_del/<str:pk>', views.adm_view_subject_del),
    path('adm_view_timetable/', views.adm_view_timetable),
    path('adm_view_tutor/', views.adm_view_tutor),
    path('adm_view_tutors_subject/', views.adm_view_tutors_subject),
    path('adm_view_tutors_subject_del/<str:pk>', views.adm_view_tutors_subject_del),
    path('adm_view_vacancy/', views.adm_view_vacancy),
    path('adm_view_vacancy_del/<str:pk>', views.adm_view_vacancy_del),
    path('adm_view_yearly_salary_reports)/', views.adm_view_yearly_salary_reports),
    path('adm_view_tutor_del/<str:pk>',views.adm_view_tutor_del),
    path('adm_update_batch_post/',views.adm_update_batch_post),
    path('adm_update_class_post/',views.adm_update_class_post),
    path('adm_update_tutor_post/',views.adm_update_tutor_post),

    path('ab/',views.ab),
    path('adm_search_tutors_post/',views.adm_search_tutors_post),
    path('adm_search_fee_structure_post/',views.adm_search_fee_structure_post),
    path('adm_search_attendence_of_tutors_post/',views.adm_search_attendence_of_tutors_post),

]